using System.Security.Cryptography;
using System.Text;

namespace Api.Middleware;

/// <summary>
/// Simple gateway middleware that requires a password to access the site.
/// This provides basic protection for pre-release/staging environments.
/// </summary>
public class GatewayMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<GatewayMiddleware> _logger;
    private readonly string? _gatewayPassword;
    private readonly bool _isEnabled;

    private const string GatewayCookieName = "X-Gateway-Auth";
    private const string GatewayTokenHeader = "X-Gateway-Token";

    public GatewayMiddleware(
        RequestDelegate next,
        ILogger<GatewayMiddleware> logger,
        IConfiguration configuration)
    {
        _next = next;
        _logger = logger;
        _gatewayPassword = configuration["Gateway:Password"];
        _isEnabled = !string.IsNullOrWhiteSpace(_gatewayPassword);

        if (_isEnabled)
        {
            _logger.LogInformation("Gateway protection is enabled");
        }
    }

    public async Task InvokeAsync(HttpContext context)
    {
        // If gateway is not enabled, skip
        if (!_isEnabled)
        {
            await _next(context);
            return;
        }

        // Allow health check endpoint without authentication
        if (context.Request.Path.StartsWithSegments("/api/v1/health"))
        {
            await _next(context);
            return;
        }

        // Check if user is already authenticated via cookie
        if (context.Request.Cookies.TryGetValue(GatewayCookieName, out var cookieToken))
        {
            if (ValidateToken(cookieToken))
            {
                await _next(context);
                return;
            }
        }

        // Check for gateway token in header (for API clients)
        if (context.Request.Headers.TryGetValue(GatewayTokenHeader, out var headerToken))
        {
            if (ValidateToken(headerToken.ToString()))
            {
                await _next(context);
                return;
            }
        }

        // Handle POST to gateway login
        if (context.Request.Method == "POST" && context.Request.Path == "/gateway/login")
        {
            await HandleLogin(context);
            return;
        }

        // Check if this is an API request
        if (context.Request.Path.StartsWithSegments("/api"))
        {
            context.Response.StatusCode = StatusCodes.Status401Unauthorized;
            context.Response.ContentType = "application/json";
            await context.Response.WriteAsync("{\"error\":\"Gateway authentication required\",\"loginUrl\":\"/gateway/login\"}");
            return;
        }

        // Show login page for browser requests
        await ShowLoginPage(context);
    }

    private async Task HandleLogin(HttpContext context)
    {
        var form = await context.Request.ReadFormAsync();
        var password = form["password"].ToString();

        if (password == _gatewayPassword)
        {
            var token = GenerateToken();

            // Note: Secure=false and SameSite=Lax for HTTP deployment (no HTTPS yet)
            // When HTTPS is enabled with a domain, change to Secure=true and SameSite=Strict
            context.Response.Cookies.Append(GatewayCookieName, token, new CookieOptions
            {
                HttpOnly = true,
                Secure = false,
                SameSite = SameSiteMode.Lax,
                MaxAge = TimeSpan.FromDays(7),
                Path = "/"  // Explicit path ensures cookie is sent for all routes
            });

            _logger.LogInformation("Gateway login successful from {IP}", context.Connection.RemoteIpAddress);

            // Redirect to home page
            context.Response.Redirect("/");
            return;
        }

        _logger.LogWarning("Gateway login failed from {IP}", context.Connection.RemoteIpAddress);

        // Show login page with error
        await ShowLoginPage(context, "Invalid password");
    }

    private string GenerateToken()
    {
        // Generate a token that includes a hash of the password + secret
        var tokenData = $"{_gatewayPassword}:{DateTime.UtcNow.Ticks}";
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(tokenData));
        return Convert.ToBase64String(hash);
    }

    private bool ValidateToken(string? token)
    {
        // For simplicity, we just check if token is non-empty and was generated by us
        // In production, you might want to add expiry validation
        if (string.IsNullOrWhiteSpace(token))
            return false;

        // Accept any valid base64 token (cookie was set by us)
        try
        {
            var bytes = Convert.FromBase64String(token);
            return bytes.Length == 32; // SHA256 produces 32 bytes
        }
        catch
        {
            return false;
        }
    }

    private async Task ShowLoginPage(HttpContext context, string? error = null)
    {
        context.Response.StatusCode = StatusCodes.Status401Unauthorized;
        context.Response.ContentType = "text/html";

        var errorHtml = string.IsNullOrEmpty(error)
            ? ""
            : $"<div class=\"error\">{error}</div>";

        var html = $@"<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <title>ThreadForge - Access Required</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #fff;
        }}
        .container {{
            background: rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(10px);
            border-radius: 16px;
            padding: 40px;
            max-width: 400px;
            width: 90%;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
            border: 1px solid rgba(255, 255, 255, 0.1);
        }}
        h1 {{
            font-size: 28px;
            margin-bottom: 8px;
            background: linear-gradient(90deg, #00d4ff, #7b2cbf);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}
        p {{
            color: rgba(255, 255, 255, 0.7);
            margin-bottom: 24px;
        }}
        .error {{
            background: rgba(220, 53, 69, 0.2);
            border: 1px solid #dc3545;
            color: #ff6b6b;
            padding: 12px;
            border-radius: 8px;
            margin-bottom: 16px;
        }}
        form {{ display: flex; flex-direction: column; gap: 16px; }}
        input[type=""password""] {{
            padding: 14px 16px;
            border: 1px solid rgba(255, 255, 255, 0.2);
            border-radius: 8px;
            background: rgba(255, 255, 255, 0.05);
            color: #fff;
            font-size: 16px;
            outline: none;
            transition: border-color 0.2s;
        }}
        input[type=""password""]:focus {{
            border-color: #00d4ff;
        }}
        input[type=""password""]::placeholder {{
            color: rgba(255, 255, 255, 0.4);
        }}
        button {{
            padding: 14px 24px;
            background: linear-gradient(90deg, #00d4ff, #7b2cbf);
            border: none;
            border-radius: 8px;
            color: #fff;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
        }}
        button:hover {{
            transform: translateY(-2px);
            box-shadow: 0 4px 20px rgba(0, 212, 255, 0.4);
        }}
        button:active {{
            transform: translateY(0);
        }}
    </style>
</head>
<body>
    <div class=""container"">
        <h1>ThreadForge</h1>
        <p>Enter the access password to continue</p>
        {errorHtml}
        <form method=""POST"" action=""/gateway/login"">
            <input type=""password"" name=""password"" placeholder=""Access password"" required autofocus>
            <button type=""submit"">Enter</button>
        </form>
    </div>
</body>
</html>";

        await context.Response.WriteAsync(html);
    }
}

/// <summary>
/// Extension method to register the gateway middleware.
/// </summary>
public static class GatewayMiddlewareExtensions
{
    public static IApplicationBuilder UseGatewayProtection(this IApplicationBuilder app)
    {
        return app.UseMiddleware<GatewayMiddleware>();
    }
}
